l1 = [0]
l2 = [0]
scale = [0.4]
num_layers = [3]
layer_size = [20]
activation = ["tanh"]
max_iter = [100]
funct = "branin"
bounds = [[-5,10],[0,15]]
num_train = 1000
num_test = 100
dim = 2
outdim = 1
num_models = 2
name = 'GP'
