python run.py toml/Ackley2.toml > Ackley2_run1.txt
python run.py toml/Ackley2.toml > Ackley2_run2.txt
python run.py toml/Ackley2.toml > Ackley2_run3.txt
python run.py toml/Ackley2.toml > Ackley2_run4.txt
python run.py toml/Ackley2.toml > Ackley2_run5.txt
python run.py toml/Ackley2.toml > Ackley2_run6.txt
python run.py toml/Ackley2.toml > Ackley2_run7.txt
python run.py toml/Ackley2.toml > Ackley2_run8.txt
python run.py toml/Ackley2.toml > Ackley2_run9.txt
python run.py toml/Ackley2.toml > Ackley2_run10.txt
python run.py toml/Ackley2.toml > Ackley2_run11.txt
python run.py toml/Ackley2.toml > Ackley2_run12.txt
python run.py toml/Ackley2.toml > Ackley2_run13.txt
python run.py toml/Ackley2.toml > Ackley2_run14.txt
python run.py toml/Ackley2.toml > Ackley2_run15.txt
python run.py toml/Ackley2.toml > Ackley2_run16.txt
python run.py toml/Ackley2.toml > Ackley2_run17.txt
python run.py toml/Ackley2.toml > Ackley2_run18.txt
python run.py toml/Ackley2.toml > Ackley2_run19.txt
python run.py toml/Ackley2.toml > Ackley2_run20.txt
python run.py toml/Ackley2.toml > Ackley2_run21.txt
python run.py toml/Ackley2.toml > Ackley2_run22.txt
python run.py toml/Ackley2.toml > Ackley2_run23.txt
python run.py toml/Ackley2.toml > Ackley2_run24.txt
python run.py toml/Ackley2.toml > Ackley2_run25.txt
python run.py toml/Ackley2.toml > Ackley2_run26.txt
python run.py toml/Ackley2.toml > Ackley2_run27.txt
python run.py toml/Ackley2.toml > Ackley2_run28.txt
python run.py toml/Ackley2.toml > Ackley2_run29.txt
python run.py toml/Ackley2.toml > Ackley2_run30.txt
