python run.py toml/Ackley1.toml > Ackley1_run1.txt
python run.py toml/Ackley1.toml > Ackley1_run2.txt
python run.py toml/Ackley1.toml > Ackley1_run3.txt
python run.py toml/Ackley1.toml > Ackley1_run4.txt
python run.py toml/Ackley1.toml > Ackley1_run5.txt
python run.py toml/Ackley1.toml > Ackley1_run6.txt
python run.py toml/Ackley1.toml > Ackley1_run7.txt
python run.py toml/Ackley1.toml > Ackley1_run8.txt
python run.py toml/Ackley1.toml > Ackley1_run9.txt
python run.py toml/Ackley1.toml > Ackley1_run10.txt
python run.py toml/Ackley1.toml > Ackley1_run11.txt
python run.py toml/Ackley1.toml > Ackley1_run12.txt
python run.py toml/Ackley1.toml > Ackley1_run13.txt
python run.py toml/Ackley1.toml > Ackley1_run14.txt
python run.py toml/Ackley1.toml > Ackley1_run15.txt
python run.py toml/Ackley1.toml > Ackley1_run16.txt
python run.py toml/Ackley1.toml > Ackley1_run17.txt
python run.py toml/Ackley1.toml > Ackley1_run18.txt
python run.py toml/Ackley1.toml > Ackley1_run19.txt
python run.py toml/Ackley1.toml > Ackley1_run20.txt
python run.py toml/Ackley1.toml > Ackley1_run21.txt
python run.py toml/Ackley1.toml > Ackley1_run22.txt
python run.py toml/Ackley1.toml > Ackley1_run23.txt
python run.py toml/Ackley1.toml > Ackley1_run24.txt
python run.py toml/Ackley1.toml > Ackley1_run25.txt
python run.py toml/Ackley1.toml > Ackley1_run26.txt
python run.py toml/Ackley1.toml > Ackley1_run27.txt
python run.py toml/Ackley1.toml > Ackley1_run28.txt
python run.py toml/Ackley1.toml > Ackley1_run29.txt
python run.py toml/Ackley1.toml > Ackley1_run30.txt
