python run.py toml/Dixon_Price.toml > Dixon_price_run1.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run2.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run3.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run4.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run5.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run6.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run7.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run8.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run9.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run10.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run11.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run12.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run13txt
python run.py toml/Dixon_Price.toml > Dixon_price_run14.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run15.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run16.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run17.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run18.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run19.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run20.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run21.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run22.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run23.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run24.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run25.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run26.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run27.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run28.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run29.txt
python run.py toml/Dixon_Price.toml > Dixon_price_run30.txt
