python run.py toml/ellipsoid.toml > ellipsoid_run1.txt
python run.py toml/ellipsoid.toml > ellipsoid_run2.txt
python run.py toml/ellipsoid.toml > ellipsoid_run3.txt
python run.py toml/ellipsoid.toml > ellipsoid_run4.txt
python run.py toml/ellipsoid.toml > ellipsoid_run5.txt
python run.py toml/ellipsoid.toml > ellipsoid_run6.txt
python run.py toml/ellipsoid.toml > ellipsoid_run7.txt
python run.py toml/ellipsoid.toml > ellipsoid_run8.txt
python run.py toml/ellipsoid.toml > ellipsoid_run9.txt
python run.py toml/ellipsoid.toml > ellipsoid_run10.txt
python run.py toml/ellipsoid.toml > ellipsoid_run11.txt
python run.py toml/ellipsoid.toml > ellipsoid_run12.txt
python run.py toml/ellipsoid.toml > ellipsoid_run13.txt
python run.py toml/ellipsoid.toml > ellipsoid_run14.txt
python run.py toml/ellipsoid.toml > ellipsoid_run15.txt
python run.py toml/ellipsoid.toml > ellipsoid_run16.txt
python run.py toml/ellipsoid.toml > ellipsoid_run17.txt
python run.py toml/ellipsoid.toml > ellipsoid_run18.txt
python run.py toml/ellipsoid.toml > ellipsoid_run19.txt
python run.py toml/ellipsoid.toml > ellipsoid_run20.txt
python run.py toml/ellipsoid.toml > ellipsoid_run21.txt
python run.py toml/ellipsoid.toml > ellipsoid_run22.txt
python run.py toml/ellipsoid.toml > ellipsoid_run23.txt
python run.py toml/ellipsoid.toml > ellipsoid_run24.txt
python run.py toml/ellipsoid.toml > ellipsoid_run25.txt
python run.py toml/ellipsoid.toml > ellipsoid_run26.txt
python run.py toml/ellipsoid.toml > ellipsoid_run27.txt
python run.py toml/ellipsoid.toml > ellipsoid_run28.txt
python run.py toml/ellipsoid.toml > ellipsoid_run29.txt
python run.py toml/ellipsoid.toml > ellipsoid_run30.txt
