python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run1.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run2.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run3.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run4.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run5.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run6.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run7.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run8.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run9.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run10.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run11.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run12.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run13.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run14.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run15.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run16.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run17.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run18.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run19.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run20.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run21.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run22.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run23.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run24.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run25.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run26.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run27.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run28.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run29.txt
python run.py toml/Styblinski_Tang.toml > Styblinski_Tang_run30.txt
