python run.py toml/branin.toml > node01.txt
python run.py toml/branin.toml > node02.txt
python run.py toml/branin.toml > node03.txt
python run.py toml/branin.toml > node04.txt
python run.py toml/branin.toml > node05.txt
python run.py toml/branin.toml > node06.txt
python run.py toml/branin.toml > node07.txt
python run.py toml/branin.toml > node08.txt
python run.py toml/branin.toml > node09.txt
python run.py toml/branin.toml > node10.txt
python run.py toml/branin.toml > node11.txt
python run.py toml/branin.toml > node12.txt
