l1 = [0]
l2 = [0]
scale = [0.4]
num_layers = [3]
layer_size = [20]
activation = ["tanh"]
max_iter = [100]
funct = "branin"
bounds = [[-5,10],[0,15]]
num_train = 20
num_test = 3
dim = 2
outdim = 1
iter = 50
K = 80
num_models = 5
