funct = 'Ackley1'
num = [20, 10]
bounds = [[-30, 30], [-30, 30], [-30, 30], [-30, 30], [-30, 30], [-30, 30], [-30, 30], [-30, 30], [-30, 30], [-30, 30]]
num_models = 1
scale = [0.2]
bfgs_iter = [2000]
iteration = 200
K = 200
gamma = 0.01
num_points = 1
